server:
  port: 80
spring:
  datasource:
    username: root
    password: qwer@123
    url: jdbc:mysql://localhost:3306/AIoT
    driver-class-name: com.mysql.cj.jdbc.Driver

sa-token:
  token-name: admin
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: false

